site_name: Portal Galt

nav:
  - Home: 'home.md'
  - Visão de Produto e Projetos:
    - Cenário Atual do Cliente e Negócio: 'introducao.md'
    - Solução Proposta: 'solucao.md'
    - Estratégias de Engenharia de Software: 'estrategias.md'
    - Cronograma e Entregas: 'cronograma.md'
    - Interação entre Equipe e Cliente: 'interacao.md'
    - Lições Aprendidas: 'licoesaprendidas.md'


theme:
  name: material
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: black 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  plugins:
  - search
